# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171108_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(default='', to='projects.Skill'),
        ),
    ]
